version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./devops/docker/local/Dockerfile
    ports:
      - 5050:5050
      - 9229:9229
    volumes:
      - .:/api/
    command: yarn dev
    depends_on:
      - postgres
    links:
      - "postgres:postgres"

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - service_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  service_postgres_data:
    driver: local

networks:
  default:
    name: auth-net