version: '3'

services:
  db:
    image: postgres:13.2
    restart: unless-stopped
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_DB_PORT=5433
      - KC_DB_URL_DATABASE=keycloakdb
      - KC_DB_URL_HOST=db
      #- KEYCLOAK_IMPORT=/tmp/import-realm.json
      #- KC_IMPORT=/tmp/import-realm.json
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost:8080
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./import-realm.json:/opt/keycloak/data/import/import-realm.json
      - ./scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./themes:/opt/keycloak/themes/mol
    ports:
      - 8080:8080
    command: start-dev --import-realm
    depends_on:
      - db

networks:
  default:
    external:
      name: auth-net